version: '2.1'

services:
  localstack:
    image: localstack/localstack:0.8.10
    ports:
      - "4567-4593:4567-4593"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3
      - DATA_DIR=                  # disable persistence
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - qfa_backend_net
      
  query-files-app:
    image: j9soft/query-files-app:0.1.0
    ports:
      - "8000:8000"
    environment:
      - QFA_ENVIRONMENT_NAME=it
      - QFA_AWS_S3_ENDPOINT_URL=http://localstack:4572
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - qfa_backend_net
      
networks:
  qfa_backend_net:
